version: '2'
services:
  front:
    container_name: front
    build: ./docker/front/
    ports:
      - "80:80"
      - "8047:8047"
    links:
      - redis:redis
      - postgres:postgres
    volumes:
      - ./www:/var/www
      - ./logs:/var/log/supervisor

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker

  redis:
    image: redis
    ports:
      - "6379:6379"

  adminer:
    build: ./docker/adminer/
    ports:
      - "4001:80"
